### ISSUE TITLE
Problema al compilar el sma.

### ISSUE THREAD

**Issue by santi10218** [stefanofabi/cstrike-webadmin#1]
Hola, buen trabajo con el proyecto, esta increible! Tengo un problema al compilar el plugin y me pasa en muchos plugins tambien. Que puede ser?

Welcome to the AMX Mod X 1.8.1-300 Compiler.
Copyright (c) 1997-2013 ITB CompuPhase, AMX Mod X Team

Error: Undefined symbol "MAX_PLAYERS" on line 53
Error: Undefined symbol "MAX_PLAYERS" on line 54
Error: Undefined symbol "MAX_PLAYERS" on line 55
Error: Undefined symbol "MAX_PLAYERS" on line 56
Error: Invalid array size (negative or zero) on line 56
Error: Undefined symbol "MAX_PLAYERS" on line 59
Error: Undefined symbol "MAX_PLAYERS" on line 60
Error: Undefined symbol "MAX_PLAYERS" on line 61
Error: Undefined symbol "MAX_PLAYERS" on line 62
Error: Undefined symbol "MAX_PLAYERS" on line 63
Error: Undefined symbol "MAX_PLAYERS" on line 65
Error: Undefined symbol "client_print_color" on line 168
Warning: Indeterminate array size in "sizeof" expression (symbol "") on line 177
Warning: Indeterminate array size in "sizeof" expression (symbol "") on line 189
Warning: Indeterminate array size in "sizeof" expression (symbol "") on line 193
Warning: Indeterminate array size in "sizeof" expression (symbol "") on line 209
Error: Undefined symbol "client_print_color" on line 229
Error: Undefined symbol "client_print_color" on line 242
Error: Undefined symbol "client_print_color" on line 248
Warning: Indeterminate array size in "sizeof" expression (symbol "") on line 280
Warning: Indeterminate array size in "sizeof" expression (symbol "") on line 291
Error: Undefined symbol "client_print_color" on line 316
Error: Undefined symbol "client_print_color" on line 319
Error: Undefined symbol "client_print_color" on line 320
Error: Undefined symbol "client_print_color" on line 323
Error: Undefined symbol "client_print_color" on line 330
Error: Undefined symbol "client_print_color" on line 331
Error: Undefined symbol "client_print_color" on line 339
Error: Undefined symbol "client_print_color" on line 351
Error: Undefined symbol "client_print_color" on line 353
Error: Undefined symbol "client_print_color" on line 432
Error: Undefined symbol "MAX_PLAYERS" on line 442

Compilation aborted.
26 Errors.
Could not locate output file C:\xampp\htdocs\csadminpanel\resources\pawn\cstrike-webadmin.amx (compile failed).

**Comment by stefanofabi** [comment]
Tenes que usar las versiones nuevas de AMX Mod X
